language: node_js
node_js:
  - "12"

stages:
  - name: test
  - name: build-prerelease
    if: branch = "master" AND type = push AND fork = false
  - name: build-tiddlywiki-com
    if: branch = "tiddlywiki-com" AND type = push AND fork = false

jobs:  
  include:
    - stage: test
      script: ./bin/test.sh
    - stage: build-prerelease
      script:
        - ./bin/travis-pre-build.sh
        - export TW5_BUILD_TIDDLYWIKI='./tiddlywiki.js'
        - export TW5_BUILD_VERSION=$(./bin/get-plugin-library-version-number)
        - export TW5_BUILD_DETAILS="Prerelease built from branch '$TRAVIS_BRANCH' at commit $(git rev-parse HEAD) of $(git remote get-url origin) at $(date +'%F %T %Z')"
        - export TW5_BUILD_MAIN_EDITION='./editions/prerelease'
        - export TW5_BUILD_OUTPUT='./output/prerelease'
        - ./bin/build-site.sh || travis_terminate 1
        - ./bin/travis-push.sh || travis_terminate 1
    - stage: build-tiddlywiki-com
      script:
        - ./bin/travis-pre-build.sh
        - export TW5_BUILD_TIDDLYWIKI='./node_modules/tiddlywiki/tiddlywiki.js'
        - export TW5_BUILD_VERSION=$(./bin/get-plugin-library-version-number)
        - export TW5_BUILD_DETAILS="Built from branch '$TRAVIS_BRANCH' at commit $(git rev-parse HEAD) of $(git remote get-url origin) at $(date +'%F %T %Z')"
        - export TW5_BUILD_MAIN_EDITION='./editions/tw5.com'
        - export TW5_BUILD_OUTPUT='./output'
        - ./bin/build-site.sh || travis_terminate 1
        - ./bin/travis-push.sh || travis_terminate 1
